# Generated by Django 5.1.7 on 2025-05-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_messagereadstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
